import { Product, ProductCategory, ProductCategoryInfo } from '@/lib/types/product';

// Product Categories with detailed information
export const PRODUCT_CATEGORIES: Record<ProductCategory, ProductCategoryInfo> = {
  angle: {
    name: 'Aluminium Angle',
    nameEn: 'Aluminium Angle',
    description: 'Aluminium angles for construction and industrial applications.',
    descriptionEn: 'Aluminium angles for construction and industrial applications.',
    specifications: 'Standard sizes, length up to 6m, cutting to size.',
    specificationsEn: 'Standard sizes, length up to 6m, cutting to size.',
    applications: ['Frames', 'Structures', 'Furniture'],
    applicationsEn: ['Frames', 'Structures', 'Furniture'],
    image: '',
  },
  plate: {
    name: 'Aluminium Plate / Flat Bar',
    nameEn: 'Aluminium Plate / Flat Bar',
    description: 'Aluminium plates and flat bars for installation and production work.',
    descriptionEn: 'Aluminium plates and flat bars for installation and production work.',
    specifications: 'Various thickness options, standard and custom sizes.',
    specificationsEn: 'Various thickness options, standard and custom sizes.',
    applications: ['Engineering', 'Fastening elements'],
    applicationsEn: ['Engineering', 'Fastening elements'],
    image: '',
  },
  channel: {
    name: 'Aluminium Channel',
    nameEn: 'Aluminium Channel',
    description: 'U-shaped aluminium channel profiles.',
    descriptionEn: 'U-shaped aluminium channel profiles.',
    specifications: 'EN standards, factory quality.',
    specificationsEn: 'EN standards, factory quality.',
    applications: ['Load-bearing structures', 'Mounting systems'],
    applicationsEn: ['Load-bearing structures', 'Mounting systems'],
    image: '',
  },
  i_beam: {
    name: 'Aluminium I-beam',
    nameEn: 'Aluminium I-beam',
    description: 'Structural aluminium I-beam profiles for high loads.',
    descriptionEn: 'Structural aluminium I-beam profiles for high loads.',
    specifications: 'High strength at low weight.',
    specificationsEn: 'High strength at low weight.',
    applications: ['Industrial facilities', 'Building structures'],
    applicationsEn: ['Industrial facilities', 'Building structures'],
    image: '',
  },
  t_beam: {
    name: 'Aluminium T-beam',
    nameEn: 'Aluminium T-beam',
    description: 'T-shaped structural aluminium profiles.',
    descriptionEn: 'T-shaped structural aluminium profiles.',
    specifications: 'High strength at low weight.',
    specificationsEn: 'High strength at low weight.',
    applications: ['Industrial facilities', 'Building structures'],
    applicationsEn: ['Industrial facilities', 'Building structures'],
    image: '',
  },
  round_bar: {
    name: 'Aluminium Round Bar',
    nameEn: 'Aluminium Round Bar',
    description: 'Solid round aluminium bar.',
    descriptionEn: 'Solid round aluminium bar.',
    specifications: 'Various diameters, convenient for machining.',
    specificationsEn: 'Various diameters, convenient for machining.',
    applications: ['Parts production', 'Machine processing'],
    applicationsEn: ['Parts production', 'Machine processing'],
    image: '',
  },
  t_profile: {
    name: 'Aluminium T-profile',
    nameEn: 'Aluminium T-profile',
    description: 'Universal T-profile for connections and frames.',
    descriptionEn: 'Universal T-profile for connections and frames.',
    specifications: 'Standard size range.',
    specificationsEn: 'Standard size range.',
    applications: ['Mounting solutions', 'Structural systems'],
    applicationsEn: ['Mounting solutions', 'Structural systems'],
    image: '',
  },
  z_profile: {
    name: 'Aluminium Z-profile',
    nameEn: 'Aluminium Z-profile',
    description: 'Special aluminium Z-profile for facade and mounting systems.',
    descriptionEn: 'Special aluminium Z-profile for facade and mounting systems.',
    specifications: 'Custom manufacturing available.',
    specificationsEn: 'Custom manufacturing available.',
    applications: ['Cladding', 'Building systems'],
    applicationsEn: ['Cladding', 'Building systems'],
    image: '',
  },
  tube_round: {
    name: 'Aluminium Round Tube / Pipe',
    nameEn: 'Aluminium Round Tube / Pipe',
    description: 'Hollow aluminium round tube and pipe profiles.',
    descriptionEn: 'Hollow aluminium round tube and pipe profiles.',
    specifications: 'Various diameters and wall thickness options.',
    specificationsEn: 'Various diameters and wall thickness options.',
    applications: ['Structures', 'Engineering systems'],
    applicationsEn: ['Structures', 'Engineering systems'],
    image: '',
  },
  square_bar: {
    name: 'Aluminium Square Bar',
    nameEn: 'Aluminium Square Bar',
    description: 'Solid square aluminium bar.',
    descriptionEn: 'Solid square aluminium bar.',
    specifications: 'Standard sizes, cutting to size.',
    specificationsEn: 'Standard sizes, cutting to size.',
    applications: ['Metal structures', 'Manufacturing'],
    applicationsEn: ['Metal structures', 'Manufacturing'],
    image: '',
  },
  sheet: {
    name: 'Aluminium Sheet',
    nameEn: 'Aluminium Sheet',
    description: 'Aluminium sheets for industrial and commercial use.',
    descriptionEn: 'Aluminium sheets for industrial and commercial use.',
    specifications: 'Thickness and format on request.',
    specificationsEn: 'Thickness and format on request.',
    applications: ['Construction', 'Design', 'Manufacturing'],
    applicationsEn: ['Construction', 'Design', 'Manufacturing'],
    image: '',
  },
  threshold: {
    name: 'Aluminium Threshold',
    nameEn: 'Aluminium Threshold',
    description: 'Ready-made aluminium thresholds and accessories.',
    descriptionEn: 'Ready-made aluminium thresholds and accessories.',
    specifications: 'Various shapes and coatings.',
    specificationsEn: 'Various shapes and coatings.',
    applications: ['Interior solutions'],
    applicationsEn: ['Interior solutions'],
    image: '',
  },
  tube_square: {
    name: 'Aluminium Square Tube',
    nameEn: 'Aluminium Square Tube',
    description: 'Aluminium tubes with square cross-section.',
    descriptionEn: 'Aluminium tubes with square cross-section.',
    specifications: 'Standard sizes, cutting to size.',
    specificationsEn: 'Standard sizes, cutting to size.',
    applications: ['Frames', 'Engineering systems', 'Production systems'],
    applicationsEn: ['Frames', 'Engineering systems', 'Production systems'],
    image: '',
  },
  tube_rectangular: {
    name: 'Aluminium Rectangular Tube',
    nameEn: 'Aluminium Rectangular Tube',
    description: 'Aluminium tubes with rectangular cross-section.',
    descriptionEn: 'Aluminium tubes with rectangular cross-section.',
    specifications: 'Standard sizes, cutting to size.',
    specificationsEn: 'Standard sizes, cutting to size.',
    applications: ['Frames', 'Engineering systems', 'Production systems'],
    applicationsEn: ['Frames', 'Engineering systems', 'Production systems'],
    image: '',
  },
  custom_profile: {
    name: 'Custom Aluminium Profile',
    nameEn: 'Custom Aluminium Profile',
    description: 'Custom aluminium extrusion profile according to customer drawing.',
    descriptionEn: 'Custom aluminium extrusion profile according to customer drawing.',
    specifications: 'Manufactured to bespoke dimensions and tolerances.',
    specificationsEn: 'Manufactured to bespoke dimensions and tolerances.',
    applications: ['Engineering', 'Industrial projects', 'Architectural details'],
    applicationsEn: ['Engineering', 'Industrial projects', 'Architectural details'],
    image: '',
  },
};

// Product Catalog Data
export const CATALOG_PRODUCTS: Product[] = [
  // Aluminium Angle
  {
    id: 'angle-20x20x2',
    category: 'angle',
    name: 'Кутник 20x20x2',
    nameEn: 'Angle 20x20x2mm',
    dimensions: '20x20x2',
    pricePerMeter: 2.85,
    weightPerMeter: 0.32,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'angle-25x25x3',
    category: 'angle',
    name: 'Кутник 25x25x3',
    nameEn: 'Angle 25x25x3mm',
    dimensions: '25x25x3',
    pricePerMeter: 3.50,
    weightPerMeter: 0.41,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'angle-30x30x3',
    category: 'angle',
    name: 'Кутник 30x30x3',
    nameEn: 'Angle 30x30x3mm',
    dimensions: '30x30x3',
    pricePerMeter: 4.20,
    weightPerMeter: 0.49,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'angle-40x40x4',
    category: 'angle',
    name: 'Кутник 40x40x4',
    nameEn: 'Angle 40x40x4mm',
    dimensions: '40x40x4',
    pricePerMeter: 6.80,
    weightPerMeter: 0.87,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Plate / Flat Bar
  {
    id: 'plate-20x3',
    category: 'plate',
    name: 'Пластина 20x3',
    nameEn: 'Flat Bar 20x3mm',
    dimensions: '20x3',
    pricePerMeter: 2.20,
    weightPerMeter: 0.16,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'plate-30x5',
    category: 'plate',
    name: 'Пластина 30x5',
    nameEn: 'Flat Bar 30x5mm',
    dimensions: '30x5',
    pricePerMeter: 4.50,
    weightPerMeter: 0.41,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'plate-50x5',
    category: 'plate',
    name: 'Пластина 50x5',
    nameEn: 'Flat Bar 50x5mm',
    dimensions: '50x5',
    pricePerMeter: 7.20,
    weightPerMeter: 0.68,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Channel
  {
    id: 'channel-20x20x2',
    category: 'channel',
    name: 'Швелер 20x20x2',
    nameEn: 'Channel 20x20x2mm',
    dimensions: '20x20x2',
    pricePerMeter: 3.80,
    weightPerMeter: 0.45,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'channel-30x30x3',
    category: 'channel',
    name: 'Швелер 30x30x3',
    nameEn: 'Channel 30x30x3mm',
    dimensions: '30x30x3',
    pricePerMeter: 6.50,
    weightPerMeter: 0.78,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium I-beam
  {
    id: 'i-beam-40x40x3',
    category: 'i_beam',
    name: 'Двутавр 40x40x3',
    nameEn: 'I-beam 40x40x3mm',
    dimensions: '40x40x3',
    pricePerMeter: 8.50,
    weightPerMeter: 1.02,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'i-beam-60x60x4',
    category: 'i_beam',
    name: 'Двутавр 60x60x4',
    nameEn: 'I-beam 60x60x4mm',
    dimensions: '60x60x4',
    pricePerMeter: 14.50,
    weightPerMeter: 1.85,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Round Bar
  {
    id: 'round-bar-10',
    category: 'round_bar',
    name: 'Пруток круглий Ø10',
    nameEn: 'Round Bar Ø10mm',
    dimensions: 'Ø10',
    pricePerMeter: 1.85,
    weightPerMeter: 0.21,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'round-bar-16',
    category: 'round_bar',
    name: 'Пруток круглий Ø16',
    nameEn: 'Round Bar Ø16mm',
    dimensions: 'Ø16',
    pricePerMeter: 4.50,
    weightPerMeter: 0.55,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'round-bar-20',
    category: 'round_bar',
    name: 'Пруток круглий Ø20',
    nameEn: 'Round Bar Ø20mm',
    dimensions: 'Ø20',
    pricePerMeter: 6.80,
    weightPerMeter: 0.86,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Round Tube
  {
    id: 'tube-round-20x2',
    category: 'tube_round',
    name: 'Труба кругла Ø20x2',
    nameEn: 'Round Tube Ø20x2mm',
    dimensions: 'Ø20x2',
    pricePerMeter: 2.95,
    weightPerMeter: 0.31,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-round-25x2',
    category: 'tube_round',
    name: 'Труба кругла Ø25x2',
    nameEn: 'Round Tube Ø25x2mm',
    dimensions: 'Ø25x2',
    pricePerMeter: 3.65,
    weightPerMeter: 0.40,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-round-30x2',
    category: 'tube_round',
    name: 'Труба кругла Ø30x2',
    nameEn: 'Round Tube Ø30x2mm',
    dimensions: 'Ø30x2',
    pricePerMeter: 4.35,
    weightPerMeter: 0.49,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Square Bar
  {
    id: 'square-bar-10',
    category: 'square_bar',
    name: 'Пруток квадратний 10x10',
    nameEn: 'Square Bar 10x10mm',
    dimensions: '10x10',
    pricePerMeter: 2.15,
    weightPerMeter: 0.27,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'square-bar-15',
    category: 'square_bar',
    name: 'Пруток квадратний 15x15',
    nameEn: 'Square Bar 15x15mm',
    dimensions: '15x15',
    pricePerMeter: 4.65,
    weightPerMeter: 0.61,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Sheet
  {
    id: 'sheet-1mm',
    category: 'sheet',
    name: 'Лист 1мм',
    nameEn: 'Sheet 1mm',
    dimensions: '1000x2000x1',
    pricePerKg: 4.20,
    weightPerMeter: 2.7,
    standardLengths: [1, 2, 3],
    inStock: true,
    material: '1050-H14',
    finish: 'Mill finish',
  },
  {
    id: 'sheet-2mm',
    category: 'sheet',
    name: 'Лист 2мм',
    nameEn: 'Sheet 2mm',
    dimensions: '1000x2000x2',
    pricePerKg: 4.20,
    weightPerMeter: 5.4,
    standardLengths: [1, 2, 3],
    inStock: true,
    material: '1050-H14',
    finish: 'Mill finish',
  },
  {
    id: 'sheet-3mm',
    category: 'sheet',
    name: 'Лист 3мм',
    nameEn: 'Sheet 3mm',
    dimensions: '1000x2000x3',
    pricePerKg: 4.20,
    weightPerMeter: 8.1,
    standardLengths: [1, 2, 3],
    inStock: true,
    material: '1050-H14',
    finish: 'Mill finish',
  },

  // Aluminium Square Tube
  {
    id: 'tube-square-20x20x2',
    category: 'tube_square',
    name: 'Труба квадратна 20x20x2',
    nameEn: 'Square Tube 20x20x2mm',
    dimensions: '20x20x2',
    pricePerMeter: 3.45,
    weightPerMeter: 0.43,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-square-25x25x2',
    category: 'tube_square',
    name: 'Труба квадратна 25x25x2',
    nameEn: 'Square Tube 25x25x2mm',
    dimensions: '25x25x2',
    pricePerMeter: 4.20,
    weightPerMeter: 0.54,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-square-30x30x2',
    category: 'tube_square',
    name: 'Труба квадратна 30x30x2',
    nameEn: 'Square Tube 30x30x2mm',
    dimensions: '30x30x2',
    pricePerMeter: 5.20,
    weightPerMeter: 0.65,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },

  // Aluminium Rectangular Tube
  {
    id: 'tube-rect-20x40x2',
    category: 'tube_rectangular',
    name: 'Труба прямокутна 20x40x2',
    nameEn: 'Rectangular Tube 20x40x2mm',
    dimensions: '20x40x2',
    pricePerMeter: 4.80,
    weightPerMeter: 0.65,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
  {
    id: 'tube-rect-30x60x2',
    category: 'tube_rectangular',
    name: 'Труба прямокутна 30x60x2',
    nameEn: 'Rectangular Tube 30x60x2mm',
    dimensions: '30x60x2',
    pricePerMeter: 7.50,
    weightPerMeter: 0.97,
    standardLengths: [1, 3, 6],
    inStock: true,
    material: '6063-T5',
    finish: 'Mill finish',
  },
];
